services:
  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # This is the address that Kafka will advertise to clients
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # This is the address that Kafka will bind to for listening
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
#    volumes:
#      - var/run/docker.sock:/var/run/docker.sock
